debugging action

diff --git a/.github/actions/publish/action.yml b/.github/actions/publish/action.yml
--- a/.github/actions/publish/action.yml
+++ b/.github/actions/publish/action.yml
@@ -30,7 +30,7 @@ runs:
         PATH:    /usr/bin:/bin:${{ github.action_path }}
       run: |
         echo "Building containter images...";
-        ${{ input.custom_build_script }} || error "Building docker images failed."
+        ${{ inputs.custom_build_script }} || error "Building docker images failed."
       shell: bash
 
     - name: Push 
